generatorName: java
inputSpec: "openapi/openapi.yaml"
outputDir: "sdks/java/generated"
library: "native"
artifactId: "graph"
additionalProperties:
  groupId: "net.azisaba.graph"
  artifactId: "graph"
  artifactVersion: "0.0.1-SNAPSHOT"
  artifactUrl: "https://github.com/AzisabaNetwork/Graph"
  invokerPackage: "net.azisaba.graph"
  apiPackage: "net.azisaba.graph.api"
  modelPackage: "net.azisaba.graph.model"
  developerName: "Azisaba Network"
  developerOrganization: "Azisaba Network"
  developerOrganizationUrl: "https://www.azisaba.net"
  licenseName: "MIT License"
  licenseUrl: "https://opensource.org/license/mit"
  scmConnection: "scm:git:https://github.com/AzisabaNetwork/Graph.git"
  scmDeveloperConnection: "scm:git:ssh://git@github.com/AzisabaNetwork/Graph.git"
  scmUrl: "https://github.com/AzisabaNetwork/Graph"
  asyncNative: true
  supportUrlQuery: false
  legacyDiscriminatorBehavior: false
  useOneOfDiscriminatorLookup: true
  dateLibrary: "java8"
  useJakartaEe: false
  hideGenerationTimestamp: true
  serializationLibrary: "jackson"
