generatorName: kotlin
inputSpec: "openapi/openapi.yaml"
outputDir: "sdks/kotlin/generated"
additionalProperties:
  groupId: "net.azisaba.graph"
  artifactId: "kotlin"
  artifactVersion: "0.0.1-SNAPSHOT"
  artifactUrl: "https://github.com/AzisabaNetwork/Graph"
  packageName: "net.azisaba.graph"
  apiPackage: "net.azisaba.graph.api"
  modelPackage: "net.azisaba.graph.model"
  developerName: "Azisaba Network"
  developerEmail: ""
  developerOrganization: "Azisaba Network"
  developerOrganizationUrl: "https://www.azisaba.net"
  licenseName: "MIT License"
  licenseUrl: "https://opensource.org/license/mit"
  scmConnection: "scm:git:https://github.com/AzisabaNetwork/Graph.git"
  scmDeveloperConnection: "scm:git:ssh://git@github.com/AzisabaNetwork/Graph.git"
  scmUrl: "https://github.com/AzisabaNetwork/Graph"
  library: "jvm-retrofit2"
  serializationLibrary: "kotlinx_serialization"
  useCoroutines: true
  useResponseAsReturnType: true
  dateLibrary: "java8"
  hideGenerationTimestamp: true
