name: OpenAPI Lint

on:
  push:
    paths:
      - "openapi/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "redocly.yaml"
      - ".github/workflows/openapi-lint.yaml"

  pull_request:
    paths:
      - "openapi/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "redocly.yaml"
      - ".github/workflows/openapi-lint.yaml"

permissions:
  contents: read

jobs:
  lint:
    name: Lint OpenAPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint OpenAPI specification
        run: pnpm openapi:lint
